default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails_authentication_engine_development

test:
  <<: *default
  database: rails_authentication_engine_test
