# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb3916d52a39f7826ee2d7788b223a7864ef945c46e850458d4d337e46952a74a54cd6c112d42b60814241d8846d07d3080735f1f90c543c2637125566f9eafd

test:
  secret_key_base: 4ab2b7c42189a303fba7f37cea19b3b7bbf7a01a9081f10ab164018beeaaf1cbd59f24460fb5d0c9a1cf50d564719d58aab089a660fa3f9c19ae534d89ad9ccb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
