module RailsAuthenticationEngine
end

require 'hash_ish'

require 'rails_authentication_engine/engine'
require 'rails_authentication_engine/application_model_helpers'
require 'rails_authentication_engine/authentication_helpers'
require 'rails_authentication_engine/presenter_helpers'
require 'rails_authentication_engine/redirect_helpers'
